### ISSUE TITLE
有做Xposed模块的意向吗？

### ISSUE THREAD

**Issue by freedom-introvert** [slarkvan/Block-Pornographic-Replies#11]
安卓手机用户挺多的，爱玩机的也不少。不过手机总体使用率比电脑浏览器高，做成XPosed模块可以让推特app也实现相关功能😁

**Comment by slarkvan** [comment]
1. 有意向，有兴趣，但是目前我不会 <^^>
2. 从我个人预期来看，这个插件用一段时间，他们那些假黄推会越来越少。

结论：到时候看，反正我挺有兴趣安卓逆向的
