### ISSUE TITLE
点了一键屏蔽之后一直显示正在屏蔽中

### ISSUE THREAD

**Issue by zy1233** [slarkvan/Block-Pornographic-Replies#12]
m2 macos chrome 版本 114.0.5735.133（正式版本） (arm64)
<img width="848" alt="截屏2023-06-30 22 12 57" src="https://github.com/slarkvan/Block-Pornographic-Replies/assets/40223340/6e747db1-e0d6-4abc-a180-9ff648709fea">

**Comment by slarkvan** [comment]
这个 Block 应该是生效了，只不过我赖得整太好的交互，你刷新下页面看看，就会发现那几个被 block 了。
赖的原因是我用 原生 js 写的，DOM 操作太累。后续可以考虑优化下交互反馈~

**Comment by zy1233** [comment]
应该没有成功block，我又试了几次，然后看我账号block的人数并没有变化
