### ISSUE TITLE
关于Twitter最新浏览限额的问题

### ISSUE THREAD

**Issue by huwan** [slarkvan/Block-Pornographic-Replies#14]
7月2号Twitter开始实施临时阅读限制，限制用户可阅读的推文数量。
![SCR-20230703-jgdd](https://github.com/slarkvan/Block-Pornographic-Replies/assets/1451009/df8a8bae-9153-41e5-a7e8-fc1c2e5b8c21)

请问这个插件是否会加速耗尽阅读限额呢？谢谢开发者。

**Comment by slarkvan** [comment]
不会。

插件原理是劫持 `TwitterDetail`  的请求，请求本身是用户浏览网页主动触发的。插件本身不会主动去 call API

**Comment by huwan** [comment]
谢谢，放心了~
