### ISSUE TITLE
能不能加个取消 twitter 浏览次数限制的功能

### ISSUE THREAD

**Issue by jiechen257** [slarkvan/Block-Pornographic-Replies#16]
这个插件 [old twitter layou](https://chrome.google.com/webstore/detail/old-twitter-layout-2023/jgejdcdoeeabklepnkdbglgccjpdgpmf)， 自称实现了

**Comment by slarkvan** [comment]
插件的本意是 block 可能涉及诈骗的黄推。
「取消 twitter 浏览次数限制」本意是对系统的对抗，不适合放到这个 repo 里
