### ISSUE TITLE
Keywork list 有点过于宽泛了

### ISSUE THREAD

**Issue by aleung** [slarkvan/Block-Pornographic-Replies#17]
试了一下，发现误杀率挺高。看了一下关键词列表，有些比较粗俗的语气词也在里面，在一些情绪化的推文里面比较常见，但并不是黄推。

例如：
> 傻逼, 我草, 卧槽|你他妈|真他妈|别他吗

还有一些虽然是黄推常用，可是这些也是很正常的单词，在正常推文、简介里也会出现：
> 黄色 妈妈 阿姨 开放

另外，可能我还不太明白怎么使用：在一个推文下获取了被标记黄推，选择性的屏蔽了几个后，再打开另外的推文，获取被标记黄推，上次没有屏蔽的人会始终会留在列表里面，我感觉他们应该没有在当前推文下留言（否则一连打开几个推文都是这几个人，也太巧合了）。我只能把他们主动移出列表（就是加入白名单？），但这其实不是我的用意，只是当前还不能判定是否应该block而已。

还有一个建议，不知道可不可以加上判定条件：回复中贴了图/视频，或者引用了带贴图推文的，才加入标记？这应该是黄推很明显的判定条件。

**Comment by slarkvan** [comment]
@aleung hey，「关键词」这个其实你可以自定义的～
你下载代码，修改下你想要的「关键词」，然后按图示例
<img width="464" alt="image" src="https://github.com/slarkvan/Block-Pornographic-Replies/assets/131340443/b62a64ef-e7d0-46c1-bfed-8b57398d017b">

**Comment by slarkvan** [comment]
针对于「还有一个建议，不知道可不可以加上判定条件：回复中贴了图/视频，或者引用了带贴图推文的，才加入标记？这应该是黄推很明显的判定条件。」

目前此 Repo local-first privacy-first 版本后续应该不会有大的更新啦。建议还是自定义关键词～

**Comment by CaunterStrike2** [comment]
> 针对于「还有一个建议，不知道可不可以加上判定条件：回复中贴了图/视频，或者引用了带贴图推文的，才加入标记？这应该是黄推很明显的判定条件。」
> 
> 目前此 Repo local-first privacy-first 版本后续应该不会有大的更新啦。建议还是自定义关键词～

不可能，因为那样需要加入模型，作为一个网页插件，不可能加那么多东西。

**Comment by aleung** [comment]
@CaunterStrike2 你是指用AI去识别图像？我的建议没有那么复杂，只是判断带图还是不带图而已，不带图的推文就bypass了。

不过这两天看到一个叫做PureTwitter的chrome插件，据作者说是在后台通过图像识别等手段来判断黄推，识别出来的账号发布到黑名单中，让插件添加。这是跟本插件完全不同的思路了，完全集中化管理黑名单。

**Comment by aleung** [comment]
Close it as not going to change.

**Comment by slarkvan** [comment]
> @CaunterStrike2 你是指用AI去识别图像？我的建议没有那么复杂，只是判断带图还是不带图而已，不带图的推文就bypass了。
> 
> 不过这两天看到一个叫做PureTwitter的chrome插件，据作者说是在后台通过图像识别等手段来判断黄推，识别出来的账号发布到黑名单中，让插件添加。这是跟本插件完全不同的思路了，完全集中化管理黑名单。

或许这个插件可以做个导入、导出功能。不违背我的 privacy-first 的原则
