### ISSUE TITLE
主号被黄推屏蔽，无法看到黄推

### ISSUE THREAD

**Issue by jjuu** [slarkvan/Block-Pornographic-Replies#22]
想用另一个号识别，然后存到sqlite里以供主号屏蔽。
另外能不能加一些钩子，让有兴趣的玩家弄干图片识别。

**Comment by slarkvan** [comment]
你的建议我会考虑下。会有下一个大版本的。

**Comment by Jaime1234dj** [comment]
![Screenshot_2024-04-07-11-42-06-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/slarkvan/Block-Pornographic-Replies/assets/166324418/045505e3-fb35-4dd3-aed9-d3ae19a88e00)
