### ISSUE TITLE
被屏蔽的回复依然占用空间，影响阅读

### ISSUE THREAD

**Issue by ChaosJiang** [slarkvan/Block-Pornographic-Replies#3]
如下图，被屏蔽的回复依然占用空间，影响阅读
建议修改 https://github.com/slarkvan/Block-Pornographic-Replies/blob/main/style.css#L2 为
```
.blocked-of-porn {
  display: none !important;
}
```
本地测试有效。

![image](https://github.com/slarkvan/Block-Pornographic-Replies/assets/7876150/d6e5adc4-13ef-4689-a4d7-76f6b5cced46)

**Comment by slarkvan** [comment]
我之前试过 `node.remove()` 而不是加 css. 在 twitter 列表下拉加载更多的场景，会被 twitter js 防范成错误，导致整个界面不可用。我没试过在 `  display: none !important;`时候，下拉加载更多场景，你有空可以试试看~

**Comment by slarkvan** [comment]
@ChaosJiang 目前增加了一键屏蔽功能，可以升级使用~

**Comment by ChaosJiang** [comment]
@slarkvan 你好，经chrome浏览器测试`display: none !important;`隐藏黄推后并不影响回复加载

**Comment by slarkvan** [comment]
@ChaosJiang 感谢你的实验~

目前我的想法是当在网页出现明显的白块时候，可能会更容易让用户联想到”一键屏蔽“功能。这样可能更符合我的初心~
