### ISSUE TITLE
可否增加推文内容过滤

### ISSUE THREAD

**Issue by ailantian** [slarkvan/Block-Pornographic-Replies#6]
试了一下很多页面不是很好使比如这里
https://twitter.com/rijingzhongwen/status/1673970194988023809
检测不到，看了一下代码，似乎是根据popup的窗口属性找到user的描述等信息来过滤的，
但是用户发的推文里面有的话，还是过滤不了。

可否加上这个字段过滤？
data-testid="tweetText"

另外就是这个用户描述应该也触发了关键字，为什么检测不到呢。是因为浏览器匹配的时候按中文来的？“简介“是不是匹配失败了。
如果别的语言的话？
contentNode.innerHTML = `${user.name}@${user.screen_name}<br />简介:${user.description}`;

**Comment by slarkvan** [comment]
我刚刚修复了一个 bug，是`// "TweetWithVisibilityResults" | "Tweet"
      if (result.__typename !== "Tweet") return;` 增加了类型判断，你可以下载最新的试下，你描述的问题还是否存在，期待你的答复~

**Comment by ailantian** [comment]
为了测试一下我点击了移出列表，现在好像彻底检测不出来了，删除插件重新安装也不管用。
不过在这之前我点击检测，能够检测到几个有问题的账号。应该是检测到了。

**Comment by slarkvan** [comment]
> 为了测试一下我点击了移出列表，现在好像彻底检测不出来了，删除插件重新安装也不管用，也重启了chrome。 不过在这之前我点击检测，上面贴的测试链接页面能够检测到几个有问题的账号。应该是检测到了。

移出列表是永久白名单。除非你的打开 Chrome 的 Application 里的 Local Storage，清除 twitter 下的 `twitter_responser_whitelist`字段，就会清空永久白名单

**Comment by ailantian** [comment]
谢谢， 找了一下, Storage编辑在这里操作。
1:打开twitter网页
2:右键打开inspect，或者到more tools-》developer tools
3找到storage， 点击clear data，清空之前的操作（名单清空了）

![https://ibb.co/Sd9pzkx]

附件6个月有效期，显示”无耻“关键字会误杀一些id
目前看，上面链接的问题解决了。

**Comment by ailantian** [comment]
谢谢
