### ISSUE TITLE
开启插件会导致Youtube无法播放

### ISSUE THREAD

**Issue by liphy** [slarkvan/Block-Pornographic-Replies#8]
开启后，播放窗口一片黑。
关掉插件后刷新即播放正常。

Win 10
Chrome 114.0.5735.199（正式版本） （64 位）

**Comment by slarkvan** [comment]
好的 我今晚根据下

**Comment by slarkvan** [comment]
已修复，你升级下插件，可以试下，我本地自己验证过了。
